spring.application.name=backend

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://ashishsuryavanshi858_db_user:e-nagarsetu@cluster0.varcwmk.mongodb.net/e_nagarsetu



# Server port
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
